// Console copy in both languages. The console is an internal tool, so the strings
// live in one table rather than a translation runtime.

export type Language = 'en' | 'zh';

export const LANGUAGE_STORAGE_KEY = 'futbots.adminLanguage';

export function initialLanguage(): Language {
  const stored = localStorage.getItem(LANGUAGE_STORAGE_KEY);
  if (stored === 'en' || stored === 'zh') return stored;
  return navigator.language?.toLowerCase().startsWith('zh') ? 'zh' : 'en';
}

const COPY = {
  consoleTitle: ['Operations console', '运营后台'],
  refresh: ['Refresh', '刷新'],
  refreshing: ['Refreshing', '刷新中'],
  backToSite: ['Back to site', '返回站点'],
  readAt: ['Read', '数据读取于'],
  loading: ['Loading', '加载中'],
  loadingData: ['Loading console data…', '正在加载后台数据…'],
  starting: ['Starting the console…', '正在启动后台…'],
  noData: ['No data yet.', '暂无数据。'],
  rows: ['rows', '行'],
  of: ['of', '/'],
  reload: ['Reload', '重新加载'],
  signInTitle: ['Sign in to continue', '请先登录'],
  signInBody: ['The console is on its own domain and keeps its own session, so sign in here.', '后台在独立域名上，登录状态也是独立的，请在这里登录。'],
  adminOnlyTitle: ['Administrator access required', '需要管理员权限'],
  adminOnlyBody: ['This account is signed in but is not on the administrator list.', '这个账号已登录，但不在管理员名单里。'],
  sessionRejectedTitle: ['Your session was rejected', '登录状态已失效'],
  sessionRejectedBody: ['The account may be fine - the sign-in itself expired. Sign out and sign in again.', '账号本身可能没问题，是这次登录过期了。退出后重新登录。'],
  signedInAs: ['Signed in as', '当前账号'],
  signInGoogle: ['Continue with Google', '使用 Google 登录'],
  signInEmail: ['Sign in', '登录'],
  signingIn: ['Signing in…', '登录中…'],
  signInFailed: ['Could not sign in.', '登录失败。'],
  email: ['Email', '邮箱'],
  password: ['Password', '密码'],
  signOut: ['Sign out', '退出登录'],

  tabOverview: ['Overview', '总览'],
  tabOverviewHint: ['Today at a glance', '今日概况'],
  tabData: ['Data Console', '数据控制台'],
  tabDataHint: ['API-Football cache', 'API-Football 缓存'],
  tabModels: ['Models', '模型'],
  tabModelsHint: ['Tokens and spend', 'Token 与花费'],
  tabPredictions: ['Predictions', '预测'],
  tabPredictionsHint: ['Shared pool and settlement', '共享池与结算'],
  tabAccuracy: ['Accuracy', '准确率'],
  tabAccuracyHint: ['Settled results', '已结算结果'],
  tabAccounts: ['Accounts', '账号'],
  tabAccountsHint: ['Users and orders', '用户与订单'],
  tabTraffic: ['Traffic', '访问数据'],
  tabTrafficHint: ['Cloudflare zone analytics', 'Cloudflare 站点分析'],

  apiCallsToday: ['API-Football calls today', '今日 API-Football 调用'],
  quotaNote: ['{used} of the {limit} daily quota', '已用 {used}，日配额 {limit}'],
  noQuota: ['No quota configured', '未配置配额'],
  modelCallsToday: ['Model calls today', '今日模型调用'],
  distinctUsers: ['{n} distinct users', '{n} 个不同用户'],
  modelSpendToday: ['Model spend today', '今日模型花费'],
  costSplit: ['{reported} reported · {estimated} estimated', '{reported} 次服务商回传 · {estimated} 次本地估算'],
  requestsToday: ['Prediction requests today', '今日预测请求'],
  requestsNote: ['{cached} served from cache · {failed} failed', '{cached} 次命中缓存 · {failed} 次失败'],
  queueActive: ['Queue in flight', '队列进行中'],
  queueNote: ['Queued or running right now', '当前排队或运行中'],
  cachedMatches: ['Cached matches', '缓存比赛数'],
  cachedMatchesNote: ['Distinct fixtures in the schedule cache', '赛程缓存中的不重复比赛'],
  cronTitle: ['Scheduled refresh', '定时刷新'],
  cronEyebrow: ['Cron', '定时任务'],
  cronNote: ['The cron writes the API-Football schedule cache every 20 minutes.', '定时任务每 20 分钟写入一次 API-Football 赛程缓存。'],
  lastWrite: ['Last write', '最近写入'],
  revenueTitle: ['Confirmed revenue', '确认收入'],
  billing: ['Billing', '计费'],
  today: ['Today', '今日'],
  last7: ['Last 7 days', '近 7 日'],
  last30: ['Last 30 days', '近 30 日'],
  allTime: ['All time', '累计'],
  orders: ['{n} orders', '{n} 笔订单'],
  accountsTitle: ['Accounts', '账号'],
  users: ['Users', '用户'],
  registered: ['Registered', '注册用户'],
  newToday: ['{n} new today', '今日新增 {n}'],
  activeToday: ['Active today', '今日活跃'],
  activeNote: ['{d7} in 7d · {d30} in 30d', '近 7 日 {d7} · 近 30 日 {d30}'],
  paidAccess: ['Paid access', '付费用户'],
  paidNote: ['Entitlements still valid', '权益仍在有效期内'],
  ordersLabel: ['Orders', '订单'],
  ordersNote: ['{pending} pending · {failed} failed', '{pending} 待处理 · {failed} 失败'],

  cachedCompetitions: ['Cached competitions', '缓存赛事数'],
  oddsVerified: ['Odds verified', '已验证赔率'],
  oddsVerifiedNote: ['Only these are offered to users', '只有这些会展示给用户'],
  refreshDelays: ['Refresh delays', '刷新受限'],
  refreshDelaysNote: ['Competitions rate limited on their last check', '上次检查被限流的赛事'],
  cacheReadAt: ['Cache read at', '缓存读取于'],
  scheduleCache: ['Schedule cache', '赛程缓存'],
  scheduleCacheNote: ['Rows come from Supabase, not a live provider call. Open a fixture to spend one API-Football request on its full context.', '这些行来自 Supabase，不是实时请求。点开某场比赛会消耗一次 API-Football 请求来拉取完整数据。'],
  searchMatch: ['Team, competition or fixture ID', '球队、赛事或 Fixture ID'],
  allCompetitions: ['All competitions', '全部赛事'],
  anyStatus: ['Any status', '全部状态'],
  statusOdds: ['Odds verified', '已验证赔率'],
  statusNoOdds: ['No odds', '无赔率'],
  statusDelayed: ['Rate limited', '被限流'],
  colCompetition: ['Competition', '赛事'],
  colMatch: ['Match', '比赛'],
  colKickoff: ['Kickoff (Shanghai)', '开赛时间（北京）'],
  colFixtureId: ['Fixture ID', 'Fixture ID'],
  colOdds: ['Odds', '赔率'],
  colLastCheck: ['Last check', '最近检查'],
  colCachedAt: ['Cached at', '缓存时间'],
  inspect: ['Inspect', '查看'],
  loadingCache: ['Loading the Supabase cache…', '正在加载 Supabase 缓存…'],
  noRows: ['No rows match these filters.', '没有符合筛选条件的数据。'],
  competitionUsage: ['Competition usage', '赛事用量'],
  costByLeague: ['Cost by league', '按赛事成本'],
  competitionUsageNote: ['Competitions burning tokens on very little cached data are worth reviewing — small leagues carry thin evidence.', '缓存数据很少却烧掉大量 token 的赛事值得复查——小联赛的数据往往很稀薄。'],
  duplicateFixtures: ['Duplicate fixtures', '重复比赛'],
  duplicateLeagues: ['Duplicate league writes', '重复赛事写入'],
  needsReview: ['Needs review', '待复查'],
  review: ['review', '复查'],
  colCached: ['Cached', '缓存'],
  colImports: ['Imports', '导入'],
  colPredictions: ['Predictions', '预测'],
  colModelCalls: ['Model calls', '模型调用'],
  colFailed: ['Failed', '失败'],
  colTokens: ['Tokens', 'Token'],

  callsAllTime: ['Calls all time', '累计调用'],
  tokensAllTime: ['Tokens all time', '累计 Token'],
  spendAllTime: ['Spend all time', '累计花费'],
  unpricedCalls: ['Calls without a price', '无价格调用'],
  unpricedNote: ['Provider returned no cost and no rate table matched', '服务商没有回传成本，本地价目表也没匹配上'],
  allPriced: ['Every call is costed', '每次调用都有成本'],
  errorsAllTime: ['Errors all time', '累计错误'],
  usageByDay: ['Usage by day', '按天用量'],
  perModel: ['Per model', '按模型'],
  usageAllTime: ['Usage all time', '累计用量'],
  calls: ['Calls', '调用'],
  tokens: ['Tokens', 'Token'],
  spend: ['Spend', '花费'],
  errors: ['Errors', '错误'],
  colModel: ['Model', '模型'],
  colProvider: ['Provider', '服务商'],
  colInput: ['Input', '输入'],
  colOutput: ['Output', '输出'],
  colTotalTokens: ['Total tokens', '总 Token'],
  colSpend: ['Spend', '花费'],
  colCostSource: ['Cost source', '成本来源'],
  unpriced: ['unpriced', '无价格'],
  reported: ['{n} reported', '{n} 次回传'],
  estimated: ['{n} estimated', '{n} 次估算'],
  none: ['none', '无'],

  runsTitle: ['Prediction runs', '预测运行记录'],
  runsEyebrow: ['Pipeline log', '流水线日志'],
  runsNote: ['One row per prediction the pipeline actually generated, with what each expert node cost. A request served from the shared pool is not here, because nothing ran.', '流水线真正跑过的每一次预测各一行，含每个专家节点的花费。命中共享池的请求不在这里——因为没有实际运行。'],
  runsEmpty: ['No runs recorded yet.', '暂无运行记录。'],
  colWhen: ['When', '时间'],
  colDecision: ['Decision', '判定'],
  colNodes: ['Expert nodes', '专家节点'],
  colRunCost: ['Run cost', '本次花费'],

  colModelsInPool: ['Models cached', '已入池模型'],
  poolEmpty: ['nothing cached', '池中无结果'],
  poolFailed: ['failed', '失败'],
  poolFailedNote: ['{n} model(s) failed on this fixture', '这场比赛有 {n} 个模型调用失败'],
  groupHits: ['{hits} of {total} hit', '命中 {hits}/{total}'],
  groupCount: ['{matches} matches · {picks} settled picks', '{matches} 场比赛 · {picks} 条已结算预测'],

  trafficTitle: ['Visitors by day', '每日访客'],
  trafficEyebrow: ['Cloudflare', 'Cloudflare'],
  trafficNote: ['Read from the zone\'s own request logs, so nothing is added to the request path and no beacon script is needed.', '直接读取 zone 的请求日志，不在请求路径上增加任何东西，也不需要埋点脚本。'],
  trafficRange: ['Last {days} days', '近 {days} 天'],
  peakUniques: ['Peak daily visitors', '单日访客峰值'],
  peakUniquesNote: ['Highest single day in the window', '窗口内最高的一天'],
  uniqueSum: ['Daily visitors summed', '每日访客累加'],
  uniqueSumNote: ['Counts a returning visitor once per day, so this is visits rather than people', '同一人隔天再来会重复计一次，所以这是访问数而不是人数'],
  requestsTotal: ['Requests', '请求数'],
  pageViewsTotal: ['Page views', '页面浏览'],
  bandwidth: ['Bandwidth', '流量'],
  threats: ['Threats blocked', '已拦截威胁'],
  countriesCount: ['Countries', '国家/地区数'],
  colVisitors: ['Visitors', '访客'],
  colPageViews: ['Page views', '页面浏览'],
  colBandwidth: ['Bandwidth', '流量'],
  colThreats: ['Threats', '威胁'],
  countriesTitle: ['Countries', '国家与地区'],
  countriesNote: ['This dataset counts requests per country, not visitors, and carries no sub-country detail. Ask if you want city and region — that needs recording request.cf ourselves.', '这份数据按国家统计的是请求数而不是访客数，也没有国家以下的粒度。需要城市/地区就得我们自己记录 request.cf，跟我说。'],
  colCountry: ['Country', '国家/地区'],
  colShare: ['Share', '占比'],
  trafficNotConfigured: ['Cloudflare analytics is not configured', '未配置 Cloudflare 分析'],
  trafficNotConfiguredNote: ['Set CLOUDFLARE_ZONE_ID and CLOUDFLARE_ANALYTICS_TOKEN as Worker secrets. The token needs only Zone → Analytics → Read; do not reuse the deploy token.', '把 CLOUDFLARE_ZONE_ID 和 CLOUDFLARE_ANALYTICS_TOKEN 设成 Worker secret。token 只需要 Zone → Analytics → Read 权限，不要复用部署用的那个。'],
  errorTraffic: ['Unable to read Cloudflare analytics.', '无法读取 Cloudflare 分析数据。'],

  modelCheck: ['Reachability', '连通性'],
  modelCheckTitle: ['Live model check', '模型连通性检查'],
  modelCheckNote: ['Sends one tiny request per model from the Worker. Cloudflare calls out from its own network, so this is the only result that reflects production — a model your laptop cannot reach may work fine here, and the reverse.', '从 Worker 向每个模型发一次极小的请求。Cloudflare 是用自己的网络出站的，所以只有这里的结果代表生产环境——你本机连不上的模型在这里可能完全正常，反之亦然。'],
  runCheck: ['Run check', '开始检查'],
  checking: ['Checking', '检查中'],
  reachableCount: ['{ok} of {total} models reachable', '{total} 个模型中 {ok} 个可用'],
  colLatency: ['Latency', '延迟'],
  colDetail: ['Detail', '详情'],
  reachable: ['reachable', '可用'],
  unreachable: ['blocked', '不可用'],
  notCheckedYet: ['Not checked yet.', '尚未检查。'],
  errorModelCheck: ['Unable to run the model check.', '无法执行模型检查。'],

  matchesInPool: ['Matches in pool', '池中比赛'],
  poolNote: ['{n} cached results', '{n} 条缓存结果'],
  snapshots: ['Model snapshots', '模型快照'],
  snapshotsNote: ['{n} current consensus rows', '{n} 条当前共识'],
  sharedPool: ['Shared prediction pool', '共享预测池'],
  cacheHits: ['Cache hits', '缓存命中'],
  sharedPoolNote: ['Every user asking for the same fixture and phase reuses one of these results, so a filled row costs nothing to serve again.', '同一场比赛、同一阶段的所有用户复用同一条结果，所以已填充的行再次服务不产生成本。'],
  colLastWrite: ['Last write', '最近写入'],
  weeklySettlement: ['Weekly model settlement', '每周模型结算'],
  weekOf: ['Week of {date}', '{date} 当周'],
  notSettled: ['Not settled yet', '尚未结算'],
  weeklyNote: ['Settled every Monday 00:00 Shanghai time from the previous week\'s snapshots: how each model scored, kept as a record.', '每周一 00:00（北京时间）用上周快照结算，记录各模型的表现。'],
  noWeek: ['No week has been settled yet.', '还没有结算过任何一周。'],
  colSamples: ['Samples', '样本'],
  colHits: ['Hits', '命中'],
  colAccuracy: ['Accuracy', '准确率'],
  colEligible: ['Eligible', '样本达标'],
  yes: ['yes', '是'],
  tooFew: ['too few samples', '样本不足'],
  colPhase: ['Phase', '阶段'],
  colPublished: ['Published', '已发布'],
  colSnapshots: ['Snapshots', '快照'],

  siteAccuracy: ['Site accuracy', '全站准确率'],
  siteAccuracyNote: ['{hits} hits of {total} settled picks', '{total} 条已结算预测中命中 {hits} 条'],
  matchesSettled: ['Matches settled', '已结算比赛'],
  matchesSettledNote: ['{n} fixtures carry a final score', '{n} 场比赛已有终场比分'],
  modelPredictions: ['Model predictions', '模型预测数'],
  modelPredictionsNote: ['Deduplicated per fixture and model', '按比赛和模型去重'],
  finishedNoScore: ['Finished without a score', '已结束但无比分'],
  refreshThese: ['Refresh these fixtures to settle them', '刷新这些比赛以完成结算'],
  nothingPending: ['Nothing pending', '没有待处理'],
  byModel: ['By model', '按模型'],
  byMarket: ['By market', '按玩法'],
  settledOnly: ['Settled picks only', '仅已结算预测'],
  settledPicks: ['Settled picks', '已结算预测'],
  newestFirst: ['Most recent first', '按时间倒序'],
  allModels: ['All models', '全部模型'],
  allMarkets: ['All markets', '全部玩法'],
  colSettled: ['Settled', '已结算'],
  colDate: ['Date', '日期'],
  colMarket: ['Market', '玩法'],
  colSelection: ['Selection', '选项'],
  colFinal: ['Final', '终场'],
  colResult: ['Result', '结果'],
  hit: ['hit', '命中'],
  miss: ['miss', '未中'],

  passesActive: ['{plan} passes active', '{plan} 有效通行证'],
  boughtToday: ['{n} bought today', '今日购买 {n}'],
  usersRecent: ['Most recently seen first', '按最近活跃排序'],
  searchUser: ['Email, user ID or provider', '邮箱、用户 ID 或登录方式'],
  allAccounts: ['All accounts', '全部账号'],
  paidOnly: ['Paid only', '仅付费'],
  freeOnly: ['Free only', '仅免费'],
  colAccount: ['Account', '账号'],
  colValidUntil: ['Valid until', '有效期至'],
  colRuns: ['Runs', '运行'],
  colRequests: ['Requests', '请求'],
  colCachedResp: ['Cached', '缓存'],
  colToday: ['Today', '今日'],
  colLastSeen: ['Last seen', '最近活跃'],
  noEmail: ['No email', '无邮箱'],
  free: ['free', '免费'],
  ordersByPlan: ['Orders by plan', '按套餐订单'],
  colPlan: ['Plan', '套餐'],
  colCustomers: ['Customers', '客户'],
  colCompleted: ['Completed', '已完成'],
  colPending: ['Pending', '待处理'],
  colRevenue: ['Revenue', '收入'],
  recentOrders: ['Recent orders', '最近订单'],
  colAmount: ['Amount', '金额'],
  colStatus: ['Status', '状态'],
  colCreated: ['Created', '创建时间'],
  colConfirmed: ['Confirmed', '确认时间'],
  colReason: ['Reason', '原因'],
  confirmed: ['confirmed', '已确认'],
  failed: ['failed', '失败'],
  pending: ['pending', '待处理'],

  fixture: ['Fixture {id}', '比赛 {id}'],
  close: ['Close', '关闭'],
  fetchingContext: ['Fetching the full context from API-Football…', '正在从 API-Football 拉取完整数据…'],
  competition: ['Competition', '赛事'],
  kickoff: ['Kickoff', '开赛时间'],
  status: ['Status', '状态'],
  finalScore: ['Final score', '终场比分'],
  notPlayed: ['Not played', '未开赛'],
  endpointCoverage: ['Endpoint coverage', '端点覆盖'],
  endpointNote: ['What was actually captured', '实际抓到了什么'],
  formations: ['Formations', '阵型'],
  matchNotes: ['Referee and venue', '裁判与场地'],
  lineups: ['Lineups and players', '首发与球员'],
  injuries: ['Injuries', '伤停'],
  h2h: ['Head to head', '历史交锋'],
  odds: ['Odds', '赔率'],
  standings: ['Standings', '积分榜'],
  topScorers: ['Top scorers', '射手榜'],
  events: ['Match events', '比赛事件'],
  notCaptured: ['Not captured for this fixture.', '这场比赛没有抓到这项数据。'],
  rowsCount: ['{n} rows', '{n} 行'],

  errorStart: ['Unable to start the console.', '无法启动后台。'],
  errorLoad: ['Unable to load the console.', '无法加载后台数据。'],
  errorSchedules: ['Unable to read the schedule cache.', '无法读取赛程缓存。'],
  errorFixture: ['Unable to load this fixture.', '无法加载这场比赛。']
} as const;

export type CopyKey = keyof typeof COPY;

export function createTranslator(language: Language) {
  const index = language === 'zh' ? 1 : 0;
  return (key: CopyKey, values: Record<string, string | number> = {}) => {
    const template = COPY[key][index];
    return Object.entries(values).reduce(
      (text, [name, value]) => text.replaceAll(`{${name}}`, String(value)),
      template as string
    );
  };
}

export type Translate = ReturnType<typeof createTranslator>;
